### PR TITLE
Fix deprecation on alias_method_chain, use Module#prepend instead

### PR DESCRIPTION
**Pull request by mathieujobin**

### CODE REVIEW

**Comment by henning-koch** [comment]
Thanks for the PR @mathieujobin .

This will break compatibility with Ruby < 2 and we still have some Ruby 1.8.7 projects that depend on gems that depend on cucumber_priority. On the other hand `alias_method_chain` *is* going to go away in a few years.

@kratob Let's talk about what we can do here. If we want to stay compatible with all versions of Ruby and ActiveSupport I guess we would need to use plain `alias`?

**Comment by kratob** [comment]
I agree, we probably need to use `alias_method` to stay 1.8  compatible.
Could we drop 1.8 and 1.9 support? I know we still have old projects using it, but do those really need to upgrade the gem?

**Comment by mathieujobin** [comment]
ok this is not my project. so you can ignore my opinion. but what i would do is publish one last release supporting ruby 1.x, and removing the support from that point on. i mean, even ruby no longer support those versions....

**Comment by mathieujobin** [comment]
also FYI https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

**Comment by henning-koch** [comment]
I decided to ship a non-patching version of `alias_method_chain`. As a side effect, this allowed me to drop activesupport as a dependency.

I also migrated to [Gemika](https://github.com/makandra/gemika) so we can easier test new dependency sets. We're now supporting Ruby 2.3 and Cucumber 3.0 :)

**Pull request closed without merging**
