### PR TITLE
support for cucumber 3

### PR DESCRIPTION
**Pull request by dmilisic**
Hello!

This PR addresses #5 
I hope this can be pulled. Currently your [spreewald](https://github.com/makandra/spreewald) gem doesn't work with cucumber 3 (it depends on this gem).

### CODE REVIEW

**Comment by triskweline** [comment]
Thanks for the PR.

I'm afraid we are committed to supporting Cucumber 1 and 2 in addition to 3.

**Comment by dmilisic** [comment]
Cucumber 1 and 2 will continue to work with 0.2.0 version of the gem.

I believe supporting all 3 cucumber versions with the same codebase would be difficult. But opening a new branch for cucumber 3 support (or even better new branch for cucumber 1 & 2) and using versioning such as `0.3.x` for cucumber 3 and `0.2.x` for cucumber 1 & 2 would work just fine. What do you think @triskweline?

**Comment by triskweline** [comment]
We're in the business of long-term maintenance for Rails apps, which is why we're investing a lot of effort for keeping our tools compatible with old stacks.

I relased `0.3.1` which incorporates your changes to make it compatible with Cucumber 3, but keeps compatibility with old versions.

**Comment by dmilisic** [comment]
great, thanks

**Pull request closed without merging**
